apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "padloc.dataVolumeClaimName" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dataVolume.storageSize }}
  {{- if .Values.dataVolume.storageClassName }}
  storageClassName: {{ .Values.dataVolume.storageClassName | quote }}
  {{- end }}
  {{- if not .Values.dataVolume.storageClassName }}
  storageClassName: manual
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "padloc.attachmentsVolumeClaimName" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.attachmentsVolume.storageSize }}
  {{- if .Values.attachmentsVolume.storageClassName }}
  storageClassName: {{ .Values.attachmentsVolume.storageClassName | quote }}
  {{- end }}
  {{- if not .Values.attachmentsVolume.storageClassName }}
  storageClassName: manual
  {{- end }}
