apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "padloc.fullname" . }}-pwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "padloc.name" . }}-pwa
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "padloc.name" . }}-pwa
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: pwa
          image: {{ .Values.pwa.image }}
          env:
            - name: PL_SERVER_URL
              value: "https://{{ .Values.ingress.host }}/server"
            - name: PL_PWA_URL
              value: "https://{{ .Values.ingress.host }}"
          ports:
            - name: http
              containerPort: {{ .Values.pwa.port  }}
      restartPolicy: {{ .Values.pwa.restartPolicy }}
