apiVersion: v1
kind: Service
metadata:
  name: {{ include "padloc.fullname" . }}-pwa
spec:
  selector:
    app: {{ include "padloc.name" . }}-pwa
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.pwa.port }}
    targetPort: {{ .Values.pwa.port }}
  type: ClusterIP
