apiVersion: v1
kind: Service
metadata:
  name: {{ include "padloc.fullname" . }}
spec:
  selector:
    app: {{ include "padloc.name" . }}
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.server.port }}
    targetPort: {{ .Values.server.port }}
