apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "padloc.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "padloc.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "padloc.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: server
          image: {{ .Values.server.image }}
          env:
            - name: PL_DATA_BACKEND
              value: {{ .Values.server.data.backend }}
            - name: PL_DATA_LEVELDB_DIR
              value: {{ .Values.server.data.leveldbDir }}
            - name: PL_DATA_ATTACHMENTS_BACKEND
              value: {{ .Values.server.data.attachmentsBackend }}
            - name: PL_DATA_ATTACHMENTS_DIR
              value: {{ .Values.server.data.attachmentsDir }}
            - name: PL_SERVER_CLIENT_URL
              value: "https://{{ .Values.ingress.host }}"
            - name: PL_EMAIL_BACKEND
              value: {{ .Values.server.data.emailBackend }}
          ports:
            - name: http
              containerPort: {{ .Values.server.port }}
          volumeMounts:
            - name: attachments
              mountPath: {{ .Values.server.volumes.attachments.mountPath }}
            - name: data
              mountPath: {{ .Values.server.volumes.data.mountPath  }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: '{{ include "padloc.dataVolumeClaimName" . }}'
        - name: attachments
          persistentVolumeClaim:
            claimName: '{{ include "padloc.attachmentsVolumeClaimName" . }}'
      restartPolicy: {{ .Values.server.restartPolicy }}
